{
  "trainer": "equiformer_v3_dens_trainer",
  "logger": "tensorboard",
  "hide_eval_progressbar": false,
  "task": {
    "strict_load": true
  },
  "dataset": {
    "train": {
      "format": "lmdb",
      "src": "/vast/home/logan_bolton/Github/equiformer_v3/experimental/tasks/methane_equiformer_sweep/data/methane_train100000_test80000/train",
      "transforms": {
        "normalizer": {
          "energy": {
            "mean": 0.0,
            "stdev": 1.0
          },
          "forces": {
            "mean": 0.0,
            "stdev": 1.0
          }
        }
      }
    },
    "val": {
      "format": "lmdb",
      "src": "/vast/home/logan_bolton/Github/equiformer_v3/experimental/tasks/methane_equiformer_sweep/data/methane_train100000_test80000/val",
      "transforms": {
        "normalizer": {
          "energy": {
            "mean": 0.0,
            "stdev": 1.0
          },
          "forces": {
            "mean": 0.0,
            "stdev": 1.0
          }
        }
      }
    },
    "test": {
      "format": "lmdb",
      "src": "/vast/home/logan_bolton/Github/equiformer_v3/experimental/tasks/methane_equiformer_sweep/data/methane_train100000_test80000/test",
      "transforms": {
        "normalizer": {
          "energy": {
            "mean": 0.0,
            "stdev": 1.0
          },
          "forces": {
            "mean": 0.0,
            "stdev": 1.0
          }
        }
      }
    }
  },
  "outputs": {
    "energy": {
      "shape": 1,
      "level": "system",
      "property": "energy"
    },
    "forces": {
      "irrep_dim": 1,
      "level": "atom",
      "property": "forces",
      "train_on_free_atoms": true,
      "eval_on_free_atoms": true
    }
  },
  "loss_functions": [
    {
      "energy": {
        "fn": "mae",
        "coefficient": 1
      }
    },
    {
      "forces": {
        "fn": "l2mae",
        "coefficient": 1
      }
    }
  ],
  "evaluation_metrics": {
    "primary_metric": "forces_mae",
    "metrics": {
      "energy": [
        "mae",
        "per_atom_mae"
      ],
      "forces": [
        "mae",
        "cosine_similarity",
        "magnitude_error"
      ]
    }
  },
  "model": {
    "name": "equiformer_v3",
    "use_pbc": true,
    "use_pbc_single": false,
    "otf_graph": true,
    "regress_forces": true,
    "regress_stress": false,
    "direct_prediction": false,
    "max_neighbors": 128,
    "max_radius": 10.3,
    "num_radial_basis": 20,
    "max_num_elements": 128,
    "num_layers": 1,
    "num_channels": 32,
    "attn_hidden_channels": 32,
    "num_heads": 8,
    "attn_alpha_channels": 64,
    "attn_value_channels": 16,
    "ffn_hidden_channels": 128,
    "norm_type": "merge_layer_norm",
    "lmax": 3,
    "mmax": 2,
    "attn_grid_resolution_list": [
      14,
      8
    ],
    "ffn_grid_resolution_list": [
      14,
      14
    ],
    "edge_channels": 64,
    "use_atom_edge_embedding": true,
    "use_envelope": true,
    "attn_activation": "sep-merge_gates2_swiglu",
    "use_attn_renorm": true,
    "use_add_merge": false,
    "use_rad_l_parametrization": true,
    "softcap": null,
    "ffn_activation": "sep-merge_gates2_swiglu",
    "use_grid_mlp": true,
    "use_gate_force_head": true,
    "alpha_drop": 0.0,
    "attn_mask_rate": 0.0,
    "attn_weights_drop": 0.0,
    "value_drop": 0.0,
    "drop_path_rate": 0.0,
    "proj_drop": 0.0,
    "ffn_drop": 0.0,
    "gradient_checkpointing_block_list": [
      0
    ],
    "enforce_max_neighbors_strictly": true,
    "avg_num_nodes": 1
  },
  "optim": {
    "batch_size": 65536,
    "eval_batch_size": 65536,
    "grad_accumulation_steps": 1,
    "load_balancing": false,
    "load_balancing_on_error": "warn_and_no_balance",
    "num_workers": 0,
    "lr_initial": 0.0004,
    "optimizer": "AdamW",
    "optimizer_params": {
      "weight_decay": 0.001,
      "betas": [
        0.9,
        0.95
      ]
    },
    "scheduler": "LambdaLR",
    "scheduler_params": {
      "lambda_type": "cosine",
      "warmup_factor": 0.0,
      "warmup_epochs": 0.1,
      "lr_min_factor": 0.01
    },
    "max_epochs": 10000,
    "clip_grad_norm": 100,
    "ema_decay": null,
    "eval_every": 5000,
    "checkpoint_every": 5000,
    "use_compile": false,
    "use_denoising_pos": false,
    "denoising_pos_coefficient": 10,
    "denoising_pos_params": {
      "prob": 0.0
    }
  },
  "cmd_note": {
    "name": "methane_eqv3_l3_data100000_lr4em04_seed1776",
    "seed": 1776,
    "run_dir": "/vast/home/logan_bolton/Github/equiformer_v3/experimental/tasks/methane_equiformer_sweep/runs/methane_eqv3_l3_data100000_lr4em04_seed1776"
  }
}
